In [23]:
# Import numpy
import numpy as np

In [33]:
# List of student scores
scores = np.array([50, 65, 30, 80, 25, 95, 100, 56, 71, 64])

# Calculate the average of the scores
average_score = np.mean(scores)

# Declare the average as the C grade
C_grade = average_score

# Curve the grades
for i in range(10):
    if  scores[i] < C_grade:
        scores[i]=C_grade
        
# Print the curved scores
print('Curved scores',scores)

Curved scores [ 63  65  63  80  63  95 100  63  71  64]


In [8]:
n = int(input("Enter the size of the checkerboard: "))

checkerboard = np.zeros((n,n),dtype=int) 

checkerboard[1::2,::2] = 1 
checkerboard[::2,1::2] = 1 

print(checkerboard)

Enter the size of the checkerboard: 6
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [9]:
arr1 = np.array([1,2,3,4,5]) 
arr2 = np.array([6,7,8,9,10]) 
list_of_arrays = [arr1, arr2] 

# Calculate the mean of each array in the list 
means = [np.mean(arr) for arr in list_of_arrays] 

# Print the mean of each array 
print(means) 

[3.0, 8.0]


In [15]:
arr3=np.array(([1,2],[3,4]))

# Transpose array
print(np.transpose(arr3))

# Flatten array
print(arr3.flatten())


[[1 3]
 [2 4]]
[1 2 3 4]


In [19]:
arr4=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9])

# Floor value
print(np.floor(arr4))

# Ceil value
print(np.ceil(arr4))

# rint value
print(np.rint(arr4))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [22]:
arr5=np.array(([1,2],[3,4]))

# Mean along axis=1
print(np.mean(arr5,axis=1))

# Var along axis=0
print(np.var(arr5,axis=0))

# Std along axis none
print(np.std(arr5,axis=None))

[1.5 3.5]
[1. 1.]
1.118033988749895
